server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:

    hibernate:
      ddl-auto: update